In [10]:
import import_ipynb
from Helpers import *
import pandas as pd
import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin

In [11]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [12]:
# high NAN count
high_nan_columns = ['Electrical','LotFrontage','GarageYrBlt']
no_variety_columns = ['Utilities','Condition2','Heating','PavedDrive','Street','BsmtCond','GarageFinish','GarageFinish','RoofMatl']
columnsToFillNone= ['GarageCond','BsmtQual', 'FireplaceQu', 'MiscFeature','PoolQC','Alley','Fence','MasVnrType','GarageQual', 'GarageType','BsmtFinType2','BsmtFinType1','BsmtExposure']
columnsToFillZero= ['MasVnrArea',"BsmtFinSF1","BsmtFinSF2",'BsmtUnfSF',"TotalBsmtSF","BsmtFullBath","BsmtHalfBath","GarageCars","GarageArea" ] 
ignoreUncorrelatedRate = 0.00
categoryColumns2 = ["OverallQual","OverallCond","MoSold","BsmtFullBath","FullBath","HalfBath","Fireplaces","GarageCars",'BsmtHalfBath', 'MSSubClass']
areaColumns=[i for i in train.columns if "SF" in i or 'Area' in i or 'ScreenPorch' in i]

In [13]:
class ColumnSelector(BaseEstimator, TransformerMixin):
    def __init__(self, columns):
        self.columns = columns

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        assert isinstance(X, pd.DataFrame)

        try:
            return X[self.columns]
        except KeyError:
            cols_error = list(set(self.columns) - set(X.columns))
            raise KeyError("The DataFrame does not include the columns: %s" % cols_error)



# class HomePreprocessor:
#     def __init__(self, drop_low_correlated=False):
#         self.drop_low_correlated = drop_low_correlated

#     def fit(self, X, y=None):
#         return self

#     def transform(self, X, *_):

#         if (drop_low_correlated):
#             X=X.pipe(drop_non_correlated_columns, min_corr=ignoreUncorrelatedRate)
        
#         df = df.pipe(drop_columns, columns=high_nan_columns) # high number of NA values 
#         .pipe(drop_columns, columns=no_variety_columns) # no variety

#         .pipe(fill_NA, columns=columnsToFillNone, value='None') # 
#         .pipe(fill_NA, columns=columnsToFillZero, value=0) # 
#         .pipe(get_dummies_for_category_columns, columns=X.columns[X.dtypes=="object"])
#         .pipe(get_dummies_for_category_columns, columns=categoryColumns2)
#         .pipe(set_type, 'MasVnrArea','int64')
#         .pipe(year_to_age, 'YearBuilt')
#         .pipe(year_to_age, 'YearRemodAdd')
#         .pipe(year_to_age, 'YrSold')
#         .pipe(drop_columns, columns=["Id","BedroomAbvGr"])## drop Garbage
#         .pipe(log_tranform, columns=areaColumns)       
#         return X

# train = preprocess(train).pipe(drop_non_correlated_columns, min_corr=ignoreUncorrelatedRate) 
# test_ids=test['Id']
# test = preprocess(test)

In [16]:
cs = ColumnSelector(columns=['GarageArea'])
cs.fit_transform(train)

      GarageArea
0            548
1            460
2            608
3            642
4            836
5            480
6            636
7            484
8            468
9            205
10           384
11           736
12           352
13           840
14           352
15           576
16           480
17           516
18           576
19           294
20           853
21           280
22           534
23           572
24           270
25           890
26           576
27           772
28           319
29           240
...          ...
1430         372
1431         440
1432         216
1433         451
1434         484
1435         462
1436         528
1437         774
1438         923
1439         550
1440         672
1441         420
1442         812
1443         192
1444         626
1445         240
1446         312
1447         556
1448         384
1449           0
1450           0
1451         840
1452         525
1453           0
1454         400
1455         460
1456         500
1457         252
1458         240
1459         276

[1460 rows x 1 columns]